version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todolist-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MyAppDb
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todolist-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysql", "-h", "localhost", "-uroot", "-proot", "-e", "SELECT 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  
  api:
    container_name: todolist-api
    build:
      context: ../.
      dockerfile: TodoList.API/Dockerfile
    ports:
      - "5199:5199"
    networks:
      - todolist-network
    depends_on:
      db:
        condition: service_healthy
    
  client:
    container_name: todolist-client
    build:
      context: ../TodoList.Client/.
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - todolist-network
    depends_on:
      - api

networks:
  todolist-network:
    driver: bridge

volumes:
  mysql-data: